[build]
  command = "pnpm install && pnpm build"
  publish = "out"
  base = "/"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 